### ISSUE TITLE
The examples lack the browser application use-case

### ISSUE THREAD

**Issue by 9llara** [rondinif/phytojs#1]
JavaScript and ES6 can be used in a web browser to display the user interface (UI) , for example this is the case of [SPA or Single page application](https://en.wikipedia.org/wiki/Single-page_application).

The services offered by the "phytojs" component can also be reused in applications but the [samples](https://github.com/rondinif/phytojs/tree/master/samples) don't have a case that illustrates how to import and use [@rondinif/phytojs](https://www.npmjs.com/package/@rondinif/phytojs) in a simple HTML or SPA

**Comment by rondinif** [comment]
v1.0.0 needs to fix: #2 possibly to be fixed in `v1.0.1` hotfix  version
